FBP
vais-ral/CCPi-astra pull request #78
Opened 2020-11-04 17:42 UTC by gfardell

Update all FBP GPU based algorithms to use new geometry

Create `FBP_Flexible` DataProcessor
Rename `FDK` to `FDK_Flexible` DataProcessor
Rename `FBP` to `FBP_Simple` DataProcessor

Create `FBP` DataProcessor that selects correct sub-class.

for GPU data will use either FDK_Flexible or FBP_Simple
for cpu will use FBP_Simple 2D versions

ToDo: Multi-channel version

2020-11-04 18:08 UTC, gfardell commented
Need to add unittests for FBP

2020-11-05 18:18 UTC, gfardell commented
GitHub has got confused.
FBP has been renamed to FBP_simple (not implemented by me, currently only uses 2D parallel cpu version from here)
FBP is a new super processor to do all the delegation to the right FBP/FDK processor.

2020-11-06 11:36 UTC, gfardell commented
Need to make source distance >> pixelsize in FBP hack

2020-11-06 16:06 UTC, gfardell commented
I believe this is ready to merge pending jenkins

2020-11-06 17:10 UTC, paskino requested changes

2020-11-06 17:10 UTC, paskino commented on Wrappers/Python/ccpi/astra/processors/FBP_Flexible.py
> +        super(FDK_Flexible, self).__init__( volume_geometry = volume_geometry,
I suggest to initialise the parent class and then modify the members that should be available.

2020-11-06 17:44 UTC, gfardell commented
I believe this is ready to merge pending jenkins

2020-11-07 00:20 UTC, merged